version: "3.3"

services:
  cameraai:
    container_name: cameraai
    build: .
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 82:80
    volumes:
      # - ./data_home_app_data:/home/app/data
      - CIPS-volume:/home/app/data
    restart: unless-stopped

  visiondetection:
  # sudo docker pull deepquestai/deepstack:arm64-2022.01.1
    image: deepquestai/deepstack:arm64-2022.01.1
    ports:
      - 123:5000
    environment:
      - VISION-DETECTION=True
    volumes:
      - ./data:/datastore
    restart: unless-stopped

volumes:
  CIPS-volume:    