[CONFIG]
deeplink: http://10.0.66.4:123/v1/vision/detection

[CAMERAS]
names: ["ACHTERDEUR"]


[ACHTERDEUR]
IP: 10.0.66.70
URL: http://10.0.66.70/Streaming/channels/1/picture
username: admin
password: tester
exclude_objects: ["potted_plant", "bench", "motorcycle"]
